baseURL = "https://thepoly.github.io/"
languageCode = "en-us"
title = "The Polytechnic Documentation"
theme = "hugo-book"


enableGitInfo = true
[params]
    BookRepo = 'https://github.com/thepoly/thepoly.github.io'
    BookEditPath = 'edit/hugo/content'